services:
  surikat_ftp:
    image: atmoz/sftp
    container_name: surikat_ftp
    restart: always
    volumes:
      - /home/jaalvarez2818/SurikatProjects/surikat-geoserver/geoserver_data:/home/${SFTP_USER}/data
    command: '${SFTP_USER}:${SFTP_PASS}:${SFTP_UID}'
    networks:
      - surikat-network
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.ftp.entrypoints=sftp"
      - "traefik.tcp.routers.ftp.service=ftp-service"
      - "traefik.tcp.services.ftp-service.loadbalancer.server.port=22"

networks:
  surikat-network:
    external: true
