services:
  surikat_ftp:
    image: atmoz/sftp
    container_name: surikat_ftp
    restart: always
    ports:
      - "3022:22"
    volumes:
      - /home/jaalvarez2818/SurikatProjects/surikat-geoserver/geoserver_data/rasters/geotiff:/home/${SFTP_USER}/data
    command: '${SFTP_USER}:${SFTP_PASS}:${SFTP_UID}'
    networks:
      - surikat-network

networks:
  surikat-network:
    external: true
